### PR TITLE
Use fuzzywuzzy for matching

### PR DESCRIPTION
**Pull request by shtrom**
The search matches now feel more natural and expected given the input string.

This adds a hard dependency on Python module `fuzzywuzzy`. The doc is updated to reflect this, but I couldn't find a way to automatically install the dependency... The `python-Levenshtein` one is optional, but speeds things up, and prevens fuzzywuzzy from showing a warning otherwise.

Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>

### CODE REVIEW

**Comment by CGenie** [comment]
Hello, thanks for this commit! Sorry for being inactive in this project.
I would add some modifier to this so the default exact match is still used, what do you think? I mean there is that burden of installing an additional pip package. Especially that from what I see, `python-levenshtein` requires a working C compiler. So I'd modify our python script and write a separate function `search_passwords_fuzzy` where the import would be done so that it doesn't break current functionality.

**Comment by shtrom** [comment]
AFAIK, `python-levenshtein` is optional for fuzzywuzzy. That said, you are right that this change still requires at least one additional package (`fuzzywuzzy`).

Perhaps the best approach is to have something like 
```python

use_fuzzywuzzy = True
try:
    import fuzzywuzzy
except:
    use_fuzzywuzzy = False
```

And choose the method to use (strict or fuzzy) depending on whether the import succeeded. This way it is still transparent to the user, and we could just add some documentation that if the optional modules are installed, fuzzy search will be used instead, and it can be sped up with yet another module.

**Comment by CGenie** [comment]
Ah, yes, the optional import method is fine. Could you prepare a patch?

**Comment by shtrom** [comment]
Rebased to fix the conflict.

**Comment by CGenie** [comment]
Thank you!

**Pull request merged**
