### PR TITLE
Added notification

### PR DESCRIPTION
**Pull request by TilBlechschmidt**
Since copying the password might take some time a little feedback is nice to have.

### CODE REVIEW

**Comment by CGenie** [comment]
Hello, thanks for the PR.
Personally I don't like polluting the notification space with such things as it distracts me.
Especially leaving info that I did something with passwords doesn't seem right.
Maybe you can find some other way to do this? Since yes it does take some time and would be nice to get some feedback, just not via notifications I think.

**Comment by TilBlechschmidt** [comment]
I had some issues with the passphrase request not working correctly which slowed it down considerably (multiple seconds) hence I created this notification PR.
Regardless I'd totally agree with your point.
Slightly off-topic but one feature that would be awesome is auto-type which rofi-pass had back when I was using Linux. Basically, you hit enter on a pass entry and it uses the user field and the password to type the password into the password box you previously focused.

**Comment by N4M3Z** [comment]
I think using the notification service is the correct way to do this as the workflow having no feedback is clearly an issue. You can remove notifications from Notification Center in system settings. 1password uses notifications and they don't stick around in the Notification Center after as well.

**Comment by CGenie** [comment]
OK, added :)

**Pull request merged**
